### ISSUE TITLE
Provider Fails from Linux CLI

### ISSUE THREAD

**Issue by chainzero** [cloud-j-luna/terraform-provider-akash#26]
While the Akash Terraform provider executes from MacOS without issue, attempts to execute from Linux CLI fail with message:

`Error: too many failed passphrase attempts`

The issue would appear to be access to the private key and stored with the keychain.  In MacOS a user may authorize current user access to the keychain without future passphrase entry.  However this is not possible from the Linux CLI and this necessitates a passphrase entry to access the keychain entry.  When `terraform apply` is initiated from Linux CLI > provoked transactions prompt for a passphrase entry > none is provided in the automated deployment via the provider > and after several attempts to elicit the passphrase from the user the error message provided is received.

Tested from Ubuntu 22.04 CLI.

**Comment by jatm80** [comment]
This happens also to me as well, however, I think this is a security measure on linux as the keyring is protected.  I found this solution in a different forum:
```echo -n "$pass" | gnome-keyring-daemon --replace --unlock```  perhaps this could help to unlock the keying in a automated way.

**Comment by andy108369** [comment]
@chainzero 
`terraform-provider-akash` sets `AKASH_KEYRING_BACKEND=os` by default https://github.com/cloud-j-luna/terraform-provider-akash/blob/fc8e25e2d2/akash/provider.go#L35

To make it work so that it does not ask you for the password prompt to unlock the keyring manager (when keyring backend is `os`) or to unlock your key directly (when keyring backend is `file`), you need to use the `test` keyring backend so it won't ask you for the password prompt.

To do so you have to make sure to export the following env variable:

```
export AKASH_KEYRING_BACKEND=test
```

as well as your `.tf` formula should set the same keyring backend - `test`:

```
provider "akash" {
  keyring_backend = "test"
```

**Comment by cloud-j-luna** [comment]
> To do so you have to make sure to export the following env variable:
> 
> ```
> export AKASH_KEYRING_BACKEND=test
> ```
> 
> as well as your `.tf` formula should set the same keyring backend - `test`:
> 
> ```
> provider "akash" {
>   keyring_backend = "test"
> ```

Would like to add that the `.tf` configuration takes precedence to environment variables. If you define them in your provider config there is no need to set it as an environment variable.
